

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(clock)
library(lubridate)
```
```{r}
billboard <- read_csv("../data/billboard_2000_2018_spotify_lyrics.csv")
```
EDA PORTION 
```{r}
#Removing the video link, simple title column.
billboard <- billboard |> 
  select(-c(video_link, simple_title, spotify_link, spotify_id, lyrics, analysis_url))
```

```{r}
#Changing columns to numeric
billboard <- billboard |> 
  mutate(across(c(energy, liveness, tempo, speechiness, acousticness, danceability, duration_ms, loudness, valence), as.numeric))
```

```{r}
#Removing the data with any missing information.
billboard <- 
  billboard |> 
  drop_na()
```

```{r}
#Creating a column with just the months
billboard <- billboard |> 
  mutate(date = as.Date(date, format = "%m/%d/%y"),
         month = month(date, label = TRUE))
```

```{r}
billboard <- billboard %>%
  mutate(seasons = case_when(
    month %in% c("Dec", "Jan", "Feb") ~ "Winter",
    month %in% c("Mar", "Apr", "May") ~ "Spring",
    month %in% c("Jun", "Jul", "Aug") ~ "Summer",
    month %in% c("Sep", "Oct", "Nov") ~ "Fall"
  ))
```

```{r}
#Checking if there are any Nan values
sapply(billboard, anyNA)
```
```{r}
#Arranging rows by the highest amount of weeks. 
billboard |> 
  arrange(desc(weeks))
```
```{r}
#Descriptive summary of weeks.
billboard |> 
  select(weeks) |> 
  summary()
```
```{r}
#A song above average spend more than 13 weeks on the charts.
long_charted <- 
  billboard |> 
  filter(weeks > 13)  
```

```{r}
#Checking the genre of the songs that charted the longest.
long_charted |> 
  count(broad_genre)
```

```{r}
#Plotting the amount of songs per genre. 
long_charted |> 
  count(broad_genre) |> 
  ggplot(aes(x = broad_genre, y = n)) +
  geom_col() +
  labs(title = "Number of Songs in a Genre", x="Genre", y="Count")
```

```{r}
#Checking which songs are on the charts ore than once.
 billboard[duplicated(billboard$title),] |> 
  arrange(title)
```

Below is 2 examples of songs that were on the chart a week and then back on the chart 10 days later????
```{r}
billboard |> 
  filter(title == "All I Want For Christmas Is You") 
```

```{r}
billboard |> 
  filter(title == "Shape Of You")
```

```{r}
#Checking what songs are catergorized as unknown.
long_charted |> 
  filter(broad_genre == ("unknown"))
```

```{r}
#tibble with the following columns.
chart_variables <-
  long_charted |> 
  select(energy, liveness, tempo, speechiness, acousticness, danceability, duration_ms, loudness) 
```

```{r}
#Full summary of the below variables.
summary(chart_variables)
```

```{r}
chart_variables |> 
  cor()
```

```{r}
#The means of the variables.
colMeans(chart_variables, na.rm = TRUE)
```

 How does the month impact the type of songs that are popular.
```{r}
#A Tibble with the months that are not in the summer.
summer_months <-
  long_charted |> 
  filter(seasons == "Summer")
```

```{r}
#Summary of summer months.
summer_months |>  
  dplyr::select(where(is.numeric)) |> 
  summary()
```
```{r}
summer_months |> 
  ggplot(aes(x = tempo, y = energy, color = broad_genre)) +
   geom_point()
```

```{r}
summer_months |> 
  group_by(broad_genre) |> 
  summarize(across(.cols = where(is.numeric) & !year, .fns = ~mean(., na.rm = TRUE)))
```

```{r}
billboard |> 
  group_by(broad_genre) |> 
  summarize(across(.cols = where(is.numeric) & !year, .fns = ~mean(., na.rm = TRUE)))
```

```{r}
long_charted |> 
  group_by(broad_genre) |> 
  summarize(across(.cols = where(is.numeric) & !year, .fns = ~mean(., na.rm = TRUE)))
```


```{r}
billboard |> 
  group_by(seasons) |> 
  summarize(across(.cols = where(is.numeric) & !year, .fns = ~mean(., na.rm = TRUE)))
```

```{r}
long_charted |> 
  group_by(seasons) |> 
  summarize(across(.cols = where(is.numeric) & !year, .fns = ~mean(., na.rm = TRUE)))
```


```{r}
billboard |> 
  filter(artist == "outkast")
```


```{r}
#A Tibble with the months that are not in the summer.
non_summer_months <- 
  long_charted |> 
  filter(seasons != "Summer")
```

```{r}
#Summary of non-summer months.
non_summer_months |>  
  dplyr::select(where(is.numeric)) |> 
  summary()
```

```{r}
write.csv(billboard, "../data/billboard_final\\.csv", row.names = FALSE)
```
```{r}
write.csv(long_charted, "../data/long_charted\\.csv", row.names = FALSE)
```

```{r}
write.csv(summer_months, "../data/summer_months\\.csv", row.names = FALSE)
```

```{r}
write.csv(non_summer_months, "../data/non_summer_months\\.csv", row.names = FALSE)
```

```{r}
write.csv(chart_variables, "../data/chart_variables\\.csv", row.names = FALSE)
```














































#liveness, tempo, speechiness, acousticness, danceability, duration_ms, loudness


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}
#Plotting the amount of songs per genre. 
billboard |> 
  count(broad_genre) |> 
  ggplot(aes(x = broad_genre, y = n)) +
  geom_col() +
  labs(title = "Number of Songs in a Genre", x="Genre", y="Count")
```


```{r}
#function that will find the mean of columns
find_mean <- function(summary_variable){
  billboard |> 
    summarize("mean_{{ summary_variable }}" := mean({{ summary_variable }}, na.rm = TRUE))
}
```
#liveness, tempo, speechiness, acousticness, danceability, duration_ms, loudness
```{r}
billboard |> 
  filter(broad_genre == "rap") 
find_mean(energy)
```






















```{r}
# billboard |> 
#   count(year)
```
```{r}
# years = 2017
# billboard |> 
#   filter(year == years) |> 
#   count(main_artist) |> 
#   arrange(desc(n))

```
```{r}
# billboard |> 
#   group_by(year) |> 
#   count(main_artist)
# ```
# ```{r}
# billboard |> 
#   group_by(main_artist, year) |> 
#   count()
# ```
# ```{r}
# 
# ```
# 
# ```{r}
# find_top <- function(summary_variable){
#   billboard |> 
#     filter(year == year) |> 
#   count(main_artist) |> 
#  arrange(desc(n))
#   }
# ```
# ```{r}
# year = 2017
# billboard |> 
#   find_top()
```

```{r}


```
```{r}

```

